### ISSUE TITLE
instance variable duplicity in PP2HtmlHeaderGrammar 

### ISSUE THREAD

**Issue by pavel-krivanek** [kursjan/petitparser2#1]
The instance variable #headerStart is present twice in the class PP2HtmlHeaderGrammar

**Comment by kursjan** [comment]
Thanks for reporting this! Should be fixed in [d3fa42c2a053b9bfe2e50905b970411511c70d2e](https://github.com/kursjan/petitparser2/commit/d3fa42c2a053b9bfe2e50905b970411511c70d2e)
