### ISSUE TITLE
Builds are failing for Pharo Stable and 5.0

### ISSUE THREAD

**Issue by kursjan** [kursjan/petitparser2#11]
The master branch seems to be failing for Pharo Stable and 5.0 version since [dfc1beb](https://travis-ci.org/kursjan/petitparser2/builds/225922369).

Seems like a configuration issue? Or something else? Pavel, you might have some background knowledge about this.

**Comment by pavel-krivanek** [comment]
Cyril did some changes in the related configuration, I will look at it.

**Comment by kursjan** [comment]
Pharo-5 seems to work fine now, there is still a problem with Pharo-stable, but it looks like SmalltalkCI issue. I opened [an issue](https://github.com/hpi-swa/smalltalkCI/issues/282).

**Comment by kursjan** [comment]
resolved
