### ISSUE TITLE
Comma in selectors: significance?

### ISSUE THREAD

**Issue by lukego** [kursjan/petitparser2#12]
I am really enjoying getting started with PetitParser2. The "sea" feature is really nice: it's liberating to be able to start with the part of the grammar that I am most interested in rather than the opening boilerplate. Great stuff!

One suggestion: I would find it helpful to briefly explain the convention of putting a comma at the end of a selector without a space, as in `jsOpen,` vs `jsOpen ,` which I am used to from the original PetitParser tutorial.

Just as a newbie it's not immediately obvious to me whether this is significant e.g. is the comma a part of the selector that PetitParser2 will handle specially somehow, or will the Smalltalk parser treat it as a separate token so that there is no semantic difference between the two forms, etc. I found myself waiting for an explanation that never came.

**Comment by lukego** [comment]
Closing now because I realize that `jsOpen,` is two tokens in Smalltalk and that the PetitParser vs PetitParser2 examples in the manual both used the same style.

I suppose that I was mostly confused due to the original PetitParser docs using a space and not being confident about how Smalltalk tokenizes source code. Likely more expert users won't have that issue.

**Comment by kursjan** [comment]
Hey, Thanks for your comment. I am not sure, if I 100% understand what was your issue, but I guess, you are right:

There is no difference between `jsOpen,` and `jsOpen ,` from the Smalltalk syntax point of view.

The comma itself `,` can be a "special" `binary` selector. You can try to experiment with the syntax yourself:

```Smalltalk
PP2SmalltalkGrammar new identifier parse: 'foobar'.  "parses foobar"
PP2SmalltalkGrammar new identifier parse: 'foo,bar'. "parses foo"
PP2SmalltalkGrammar new binary parse: ',bar'.        "parses only comma
```

In other words, message to an object might be:
- identifier, starting with letter and followed by letters and digits. 
- binary selector, which might be comma, question mark etc, they expect argument and can have a longer version with the `:`, like this: `comma:`, `questionMark:`, ...
- some more, not relevant now...
