### ISSUE TITLE
Debugging parse errors?

### ISSUE THREAD

**Issue by lukego** [kursjan/petitparser2#14]
How should I debug parser errors in my test suites?

I am using the Moose-6.1 image. I have the impression that the debugger is supposed to have special support for PetitParser2. However, when a test case for a parser production fails I am not really finding any useful information in the debugger.

Screenshot of what I see:

![screen shot 2017-06-05 at 11 15 39](https://cloud.githubusercontent.com/assets/13791/26778171/83282fb2-49e0-11e7-9fc6-8f7a6db83933.png)

I would find it very helpful to be able to find the errors in larger grammars. Just now it seems necessary to divide-and-conquer and have small test cases for each and every small production so that I will always encounter errors on the simplest possible examples. However, if I were able to debug parse errors on larger inputs then I would prefer to have fewer, larger test cases.

**Comment by girba** [comment]
PP2 does not yet have a debugger extension. Only PP1 has one.

**Comment by lukego** [comment]
Thanks for clarifying.

I am parsing semi-structured input (screen-scraping the output from unix commands) and I am finding bounded seas _amazing_ for this purpose. I love being able to ignore all the parts of the input that I don't care about and still work with composable and reliable parser combinators. This means that I should stick with PetitParser2 rather than PetitParser, right?

(I'm not entirely clear on how much functionality is common to both, I only learned about the concept of bounded seas when reading the PetitParser2 documentation.)

**Comment by kursjan** [comment]
Hey, from my point of view, I will maintain/develop bounded seas only in PP2. 

PP2 has better infrastructure and better performance characteristics wrt bounded seas (and of course, PP2 is a personal thing for me :)

Regarding the diffs between PP/PP2, the PP2 has all the functionality of PP and similar DSL, plus has extra features: bounded seas, parsing contexts and performance optimizations, support for streams....

**Comment by kursjan** [comment]
As a workaround you can use the workspace:

DWARFGrammar new enumeration debug: '(DW_TAG_enumeration_type ....'

I agree, this is not ideal and I will work on it...

**Comment by kursjan** [comment]
I just realized, have you tried to inspect `resultContext`? There should be a "debug view" tab...

**Comment by lukego** [comment]
@kursjan Thanks. Yes, if I dig up the `resultContext` in the debugger's inspector then it seems like I can find some useful information. Cool, though a bit hard to find.

One more error that took me a while to work out is `TestFailure: Got 60 instead of 61.` really meaning that my parser did not consume all of its input. I'm not sure what the appropriate fix is because I didn't see an `assert:equals:description:` method to add a hepful message to?
