### ISSUE TITLE
Tab With Autogenerated Samples Missing In the Browser.

### ISSUE THREAD

**Issue by deech** [kursjan/petitparser2#21]
At some point the PetitParser browser used to have a tab next to the `Code Graph` and `Source` tabs that showed autogenerated samples that would work with the current parser. That functionality seems to have disappeared over the past couple of months or so, is there any way to get it back?

**Comment by JurajKubelka** [comment]
I do not know anything about it. Looking at the code I can see the message:

```Smalltalk
PP2ParserBrowser>>#exampleIn: composite
	self flag: 'not yet supported'.
	composite text
		title: 'Example';
		useExplicitNotNil;
		display: [ :class :productionSelector | (self production: productionSelector from: class) example ];
		act: [:text | text update] icon: GLMUIThemeExtraIcons glamorousRefresh entitled: 'Generate another one'
```

Petit Parser 1 has methods like `PPParser>>#exampleOn:`. So, it looks like it is not implemented in the Petit Parser 2.

**Comment by deech** [comment]
That makes sense. Thanks!

**Comment by kursjan** [comment]
Should not be so hard to add it. More or less copy-paste from PP1.
