### ISSUE TITLE
Move to Tonel repository format?

### ISSUE THREAD

**Issue by JurajKubelka** [kursjan/petitparser2#23]
Hi @kursjan, 

do you agree to move the repository to the [Tonel format](https://github.com/pharo-vcs/tonel)? 

Source code files are per class instead of per method. It is supported in Pharo 6.1 and Pharo 7.0.

And maybe we could move sources to `src` directory?

What do you think?

**Comment by kursjan** [comment]
Is tonel the format Pharo is going to? If so, I am fine with it, but I don't have time for doing so.

**Comment by JurajKubelka** [comment]
Yes, Tones is a new format, used in Pharo. It has support in Pharo 6.1 and 7.0 by default.
I will do it :-)

**Comment by JurajKubelka** [comment]
1f32d8fa9c71bc39b94a240f4100d249bd8dad22
