### ISSUE TITLE
Do not use `ByteString` in `PP2BufferStream`

### ISSUE THREAD

**Issue by kursjan** [kursjan/petitparser2#27]
For interop with GemStone, PP2 should not use ByteString string.

**Comment by kursjan** [comment]
@jgfoster: I suppose, it would be enough to change reference from `ByteString` to `String`. I honestly do not understand how to properly work with `Streams` in Pharo. Would that solution be OK for you?

What would I need to do to support `WideString` in infuture?

**Comment by jgfoster** [comment]
@kursjan: Changing ByteString to String is good for me, thanks! 

As to Streams, I don't have enough experience with Pharo to give a good answer but I believe the issues relate instance variable names and whether the position is zero-based or one-based.

With regard to WideString, we'd need to investigate the overlap between Pharo's WideString and GemStone's DoubleByteString (or even Unicode16).
