### ISSUE TITLE
Create alternatives to `thisContext`

### ISSUE THREAD

**Issue by kursjan** [kursjan/petitparser2#28]
References to `thisContext` are troublesome for GemStone migration. Provide alternatives.

`thisCotnext` is referenced from these methods:
- `PP2RecordingContext>>node`
- `PP2RecordingContext>>strategy`

**Comment by kursjan** [comment]
@jgfoster: James, any ideas what are my options here? I have no idea how to deal with this.

**Comment by jgfoster** [comment]
I'll do some investigation and let you know what I come up with.

**Comment by jgfoster** [comment]
If `PP2RecordingContext>>node` called `PP2RecordingContext>>strategy` then you would reduce duplicate code and we would have only one method to fix.

**Comment by kursjan** [comment]
For you convenience, I implemented the following method:
```
PP2RecordingContext#findContextSuchThat: aBlock
	^ thisContext findContextSuchThat: aBlock
```

**Comment by jgfoster** [comment]
Yes, that helps. I can replace that method as a minimal change. Thanks.
