### ISSUE TITLE
Purpose of ManifestPetitParser and ManifestPetitParserTests?

### ISSUE THREAD

**Issue by jgfoster** [kursjan/petitparser2#41]
When I load PetitParser2 into GemStone I get a warning that PackageManifest must be defined. It appears that this is so ManifestPetitParser and ManifestPetitParserTests can have a superclass. What is the role of these classes? If they are related to developer tools (code-critics, ruleRB*), then could they be placed in another package?

**Comment by kursjan** [comment]
Good question, seems to be code-critics specific... remvoed
