### ISSUE TITLE
PetitParser2 Gui Crash

### ISSUE THREAD

**Issue by mahugnon** [kursjan/petitparser2#50]
PetitParser2 GUI crash because it is base on Pharo method `#ultimateSourceCodeAt:ifAbsent:` which have been removed. It is suggested to use `#lookupSelector:`  instead.
https://github.com/pharo-project/pharo/commit/420f92c9c304255df6d7a1a4687616bcbe064da7#diff-6413a3cb85ceeadda98e063a84622272

**Comment by kursjan** [comment]
Thanks!
